services:
  - type: worker
    name: discord-ticket-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MTU0ODc3ODcyMDQzOTk1OTcwMg.GxZ45f.HfYjTzpOLmp5RzqUFS3BOh9BFBYpkxF0YUuy3c
        sync: false